title: "Oleks Sobol"
name: "Oleks Sobol"
description: "Projects, experiments, and late-night hacks."
url: "https://olekssobol.github.io"
baseurl: ""  

# Minimal Mistakes via remote theme
remote_theme: "mmistakes/minimal-mistakes@4.26.0"
minimal_mistakes_skin: "dark" # try: default, air, aqua, neon, etc.

# Plugins supported by GitHub Pages
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

#
author:
  name: "Oleks Sobol"
  avatar: "/assets/images/avatar.png" # add if you want
  bio: "Backend dev automating the boring stuff away | 95% faster onboarding, 90% fewer bugs"
  location: "Washington, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/OleksSobol"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/olekssobol/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:olekssobol@gmail.com"
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/@Life2freedom"

# Defaults for pages/posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Collections
collections:
  posts:
    output: true
  pages:
    output: true
    permalink: /:title/

# Include pages directory
include:
  - _pages
